name: Deploy Firebase Functions on merge
'on':
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/firebase-functions-merge.yml'
      - '.github/workflows/firebase-functions-pull-request.yml'
jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Create venv and install dependencies
        run: |
          cd functions
          python3.13 -m venv venv
          . venv/bin/activate && python3.13 -m pip install -r requirements.txt
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPLIT_CHECK_41CB9 }}'
      - name: Deploy Functions
        run: npx firebase-tools deploy --only functions --project split-check-41cb9
